import { Web3ReactProvider } from '@web3-react/core'
import Navbar from './Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { MetaMask } from '@web3-react/metamask'
import { WalletConnect } from '@web3-react/walletconnect'
import { ReactNode, useEffect } from 'react'
import { Web3ContextProvider } from '@/libs/components/Web3ContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Web3ContextProvider>
          <Navbar />
        {children}
        </Web3ContextProvider>
        </body>
    </html>
  )
}